In [1]:
import numpy as np

array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [2]:
type(array1)

numpy.ndarray

In [3]:
array1.shape

(11,)

In [4]:
array1.size

11

In [5]:
array2 = np.random.random(8)
array2

array([0.32963902, 0.37174133, 0.15126067, 0.9947556 , 0.25526635,
       0.1430706 , 0.74406157, 0.20712843])

In [6]:
array3 = np.arange(2, 8, 2)

In [7]:
array3

array([2, 4, 6])

In [8]:
array4 = np.arange(1, 9)
array4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
array4[2:3] # 인덱싱과 슬라이싱은 대괄호 안에서 진행

array([3])

In [11]:
for i in range(10):
    i += 1
    print(i)

1
2
3
4
5
6
7
8
9
10


In [13]:
array5 = np.full(10, 2)
array5

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [17]:
filter = np.where(array1 > 4) # 핵심코드

In [18]:
array1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

In [20]:
array1.max()

31

In [21]:
array1.min()

2

In [22]:
array1.mean()

14.545454545454545

In [23]:
array1.std()

9.680004098079865

In [24]:
array1.var()

93.70247933884298

In [25]:
np.median(array1)

13.0

In [26]:
filter = np.where(array1 > 6)

In [27]:
array1[filter]

array([ 7, 11, 13, 17, 19, 23, 29, 31])

In [28]:
import numpy as np 

revenue_in_yen = [ 300000, 340000, 320000, 360000, 440000, 140000, 180000, 340000, 330000, 290000, 280000, 380000, 
                  170000, 140000, 230000, 390000, 400000, 350000, 380000, 150000, 110000, 240000, 380000, 380000, 340000, 
                  420000, 150000, 130000, 360000, 320000, 250000 ]

In [29]:
yen = np.array(revenue_in_yen)

In [30]:
filter = np.where(yen <= 200000)

In [31]:
yen[filter]

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])